apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse
spec:
  replicas: {{ .Values.clickhouse.replicaCount }}
  serviceName: clickhouse
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      {{- if .Values.clickhouse.affinity }}
      affinity:
{{ toYaml .Values.clickhouse.affinity | indent 8 }}
      {{- end -}}
      {{- if .Values.clickhouse.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.clickhouse.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.clickhouse.tolerations }}
      tolerations:
{{ toYaml .Values.clickhouse.tolerations | indent 8 }}
      {{- end }}
      volumes:
        - name: clickhouse-configd
          configMap:
            name: clickhouse-configd
      containers:
        - name: clickhouse-server
          image: "{{ .Values.clickhouse.repository }}:{{ .Values.clickhouse.tag }}"
          imagePullPolicy: {{ .Values.clickhouse.pullPolicy }}
          terminationMessagePath: "/var/log/clickhouse-server/clickhouse-server.err.log"
          ports:
          - name: rpc
            containerPort: 9000
            protocol: TCP
          - name: rest
            containerPort: 8123
            protocol: TCP
          - name: interserver
            containerPort: 9009
            protocol: TCP
          volumeMounts:
          - name: clickhouse-data
            mountPath: {{ .Values.clickhouse.persistence.mountPath }}
          - name: clickhouse-configd
            mountPath: /etc/clickhouse-server/config.d/remote_servers.xml
            subPath: remote_servers.xml
          - name: clickhouse-configd
            mountPath: /etc/clickhouse-server/config.d/zookeeper.xml
            subPath: zookeeper.xml
          - name: clickhouse-configd
            mountPath: /etc/clickhouse-server/config.d/graphite.xml
            subPath: graphite.xml
          - name: clickhouse-configd
            mountPath: /etc/clickhouse-server/users.d
          resources:
{{ toYaml .Values.clickhouse.resources | indent 12 }}

  volumeClaimTemplates:
  - metadata:
      name: clickhouse-data
    spec:
      accessModes:
      {{- range .Values.clickhouse.persistence.accessModes }}
        - {{ . | quote }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.clickhouse.persistence.size }}
